### ISSUE TITLE
Docs: Add README and Setup instructions

### ISSUE THREAD

**Issue by bismitaguha** [anitab-org/open-source-programs-web#1]
### Is your feature request related to a problem? Please describe.
- There is no guide for what this repository is meant for.
- No guidelines to setup this project.
### Describe the solution you'd like
- Add an initial README.md which describes the purpose of the repository, with relevant links.
- Add a SETUP.md with instructions to set up this project, with required libraries and packages for the purpose.
### Describe alternatives you've considered
N/A
### Additional context
N/A

**Comment by abha224** [comment]
closing this since the mentioned task has already been completed.
