### ISSUE TITLE
Bug: Remove irrelevant options from checklist in PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-web#100]
### Describe the bug
There is a option ` I have written Kotlin Docs whenever is applicable` under the checklist in PULL_REQUEST_TEMPLATE.md. (I think due to copy-pasting the file from some other project).

### To Reproduce
1. Go to https://github.com/anitab-org/open-source-programs-web/blob/develop/.github/PULL_REQUEST_TEMPLATE.md
2. See error

### Expected behavior
The option should be removed from the checklist.

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@isabelcosta @codesankalp Can you please add labels to it. This can be a good `First Timers only` issue. 🙂

**Comment by isabelcosta** [comment]
awesome catch @Rahulm2310 ;) thank you so much! Also I added the first timers only issue, but if you wish to do this, its also fine ;) you found it. just saying

**Comment by ashwinijha6** [comment]
@codesankalp could you pls assign this to @mehakkkk  this has not been assigned

**Comment by keshakaneria** [comment]
> @codesankalp could you pls assign this to @mehakkkk this has not been assigned

Oops, we missed out assigning her! But we cant see her username to assign :(

**Comment by Aaishpra** [comment]
@mehakkkk please comment here so that you can be assigned to this issue, and do follow contribution guidelines from next time.

**Comment by ashwinijha6** [comment]
> > @codesankalp could you pls assign this to @mehakkkk this has not been assigned
> 
> Oops, we missed out assigning her! But we cant see her username to assign :(

Yeah @keshakaneria

**Comment by codesankalp** [comment]
I will assign this to @mehakkk when she will comment here @keshakaneria, @Aaishpra, and @ashwinijha6.
I have asked her to do so in the PR and waiting for her comment on this issue.

**Comment by devika1822** [comment]
hii, can you assign this to me?

**Comment by samilieberman** [comment]
Hi @Rahulm2310 @isabelcosta @codesankalp
Can I work on this issue? :)

**Comment by Aaishpra** [comment]
@samilieberman assigned you. If you need any help feel free to reach out.

**Comment by samilieberman** [comment]
Hey @Aaishpra,
Thank you! I raised a PR: https://github.com/anitab-org/anitab-forms-web/pull/144
