### ISSUE TITLE
Bug: Incorrect link to zulip stream in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-web#108]
### Describe the bug
The link to [#open-source-progs](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs) stream in CONTRIBUTING.md is incorrect. 

### To Reproduce
1. Go to https://github.com/anitab-org/open-source-programs-web/blob/develop/.github/CONTRIBUTING.md
2. Click on `#open-source-progs`
3. See error

### Expected behavior
The link should be corrected to [https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@isabelcosta @codesankalp Please add labels to this. This can be a good `First timers only` issue.

**Comment by codesankalp** [comment]
@Rahulm2310 It's showing correct to me.
![image](https://user-images.githubusercontent.com/56037184/110015159-94f37580-7d49-11eb-86f5-a8c776e835bf.png)
The page is opening a modal for joining the stream.

**Comment by Rahulm2310** [comment]
@codesankalp Yes for me as well, but the correct stream link should be https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs

**Comment by keshavagarwal17** [comment]
I would like to work on this issue.

**Comment by codesankalp** [comment]
@The-Keshav-Agarwal Wait for issue confirmation and labels addition by @isabelcosta

**Comment by isabelcosta** [comment]
I will add the labels. but feel free @codesankalp to approve issues and add the labels, since you are an OS leader :)

**Comment by keshavagarwal17** [comment]
@isabelcosta @codesankalp please add the labels so that I can work on this.

**Comment by codesankalp** [comment]
Assigning you @The-Keshav-Agarwal.
