### ISSUE TITLE
Bug : Incorrect link to reporting guidelines in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-web#109]
### Describe the bug
The links to reporting guidelines is incorrect in the code of conduct file.

### To Reproduce
1. Go to 'https://github.com/anitab-org/open-source-programs-web/blob/develop/CODE_OF_CONDUCT.md'
2. Scroll down to Reporting guidelines section
3. Click on [Reporting Guidelines](https://github.com/anitab-org/open-source-programs-web/blob/develop/reporting_guidelines.md)

### Expected behavior
Links to the file should be corrected :

Reporting guidelines: https://github.com/anitab-org/open-source-programs-web/blob/develop/REPORTING_GUIDELINES.md

### Screenshots
![Bug_reporting](https://user-images.githubusercontent.com/66437295/110089188-cc9b0580-7dbb-11eb-8383-1f841fc9e5c6.gif)

**Comment by Amulya-coder** [comment]
@isabelcosta can you please add a label to it as `First-Timer only issue`. Thanks 🙂

**Comment by nlok5923** [comment]
I would like to work on it it will be mine first contribution to this project.

**Comment by codesankalp** [comment]
@nlok5923 **Assigning you.**
