### ISSUE TITLE
Change links and text to the current repository name

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-web#120]
## Description
As a contributor,
I need all the links and text that is using `open-source-programs-web` changed into `anitab-forms-web`,
so that there is no confusion and 404 pages for newcomers.

### Update [Required]
- [ ] Change `open-source-programs-backend` to `anitab-forms-backend`.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours.

**Comment by keshavagarwal17** [comment]
@codesankalp I would like to work on this issue.

**Comment by Aaishpra** [comment]
@The-Keshav-Agarwal assigned you.
Happy Documenting 🚀

**Comment by prykdev** [comment]
I'd like to work on this if it is available. : )

**Comment by keshavagarwal17** [comment]
@P-riyanka-prasad as I already made a PR for this issue and it is under review so you can work on another issue.

**Comment by codesankalp** [comment]
@P-riyanka-prasad Do you want to work on this issue?

**Comment by prykdev** [comment]
Yes

**Comment by codesankalp** [comment]
Assigning you @P-riyanka-prasad.

**Comment by codesankalp** [comment]
Any progress update @P-riyanka-prasad ?

**Comment by Aaishpra** [comment]
Unassigning @P-riyanka-prasad due to no response

**Comment by untari** [comment]
Hi, it's anyone working on this issue? 
if not may I work on it?

**Comment by codesankalp** [comment]
Yes, @untari.
Assigning you.
