### ISSUE TITLE
Chore: Add all-contributors bot configuration

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#124]
## Description

As a maintainer,
I need to configure an all-contributors bot,
so that I can better recognize the contributors and leaders of this project.

   

-  https://allcontributors.org/docs/en/bot/configuration

### Update [Required]

- [ ] Add configuration to project https://allcontributors.org/docs/en/bot/configuration

 

- [ ]    Add first contributors to table

## Definition of Done

- [ ] All of the required items are completed.

    

- [x] Approval by 1 mentor.

## Estimation

1 hour

**Comment by isabelcosta** [comment]
@all-contributors please add @codesankalp for maintenance

**Comment by isabelcosta** [comment]
@all-contributors please add @Aaishpra for maintenance

**Comment by isabelcosta** [comment]
@all-contributors please add @keshakaneria for maintenance
