### ISSUE TITLE
[docs] Migrate docusaurus deployment from surge to gh-pages

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-web#126]
### Is your feature request related to a problem? Please describe.
It will be better to have the docs on the github-pages.

### Describe the solution you'd like
Deploy the docs on gh-pages.
Take reference from this: https://github.com/anitab-org/mentorship-backend/pull/841/commits/4cc78ae98b058a2eb2ad33adf1018e19e3a70e54

**Comment by Harshita-Kanal** [comment]
I would like to take this up, a bit new here, can I get some guidance to get started?

**Comment by codesankalp** [comment]
Assigning you @Harshita-Kanal

**Comment by codesankalp** [comment]
@Harshita-Kanal If you need any help or any guidance you can ask it on Zulip of Anitab-org.

**Comment by Harshita-Kanal** [comment]
Made a PR, do suggest changes on the same
