### ISSUE TITLE
Fix QA-Checks

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-web#130]
### Describe the bug
See the QA-Checks. It is failing.

### To Reproduce
1. Run QA checks as mentioned in README.

### Expected behavior
QA-Checks must pass.

**Comment by Amulya-coder** [comment]
@codesankalp if no one is working on this issue I would like to work.

**Comment by codesankalp** [comment]
Assigning you @Amulya-coder

**Comment by codesankalp** [comment]
@Amulya-coder Can you update your progress?

**Comment by Amulya-coder** [comment]
@codesankalp I have done some research on why the QA-checks are failing and made some changes, but how do I check if my made changes working fine or not and QA-checks are passing.

**Comment by codesankalp** [comment]
@Amulya-coder push your branch on GitHub or simply you can make aPR to see the build.

**Comment by Amulya-coder** [comment]
![image](https://user-images.githubusercontent.com/66437295/116736754-eea4b300-aa0d-11eb-9151-3e8bb37a04ad.png)

@codesankalp Is it fine can you please confirm.

**Comment by codesankalp** [comment]
Please make a PR and I will review it.
