### ISSUE TITLE
Add a check before committing locally

### ISSUE THREAD

**Issue by nellyk** [anitab-org/open-source-programs-web#156]
### Describe the bug

Currently when commiting changes no checks are made to ensure that the changes made do not broken any of the tests/linting. These can introduce bugs.

I propose the use of husky https://github.com/typicode/husky which would add a pre commit hook

### To Reproduce
Try committing any changes locally with an error, this will pass through correctly without any errors.

### Expected behavior

A message preventing the committing of changes unless the errors are resolved locally.

**Comment by codesankalp** [comment]
It's good to have the pre-commit hook, so it seems to be a valid enhancement.
Make sure `husky` should be in development packages.
