### ISSUE TITLE
Fix docusaurus deployment configuration

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-web#167]
## Description

As a maintainer,
I need Docusaurus release action fixed,
So that documentation can be available on GitHub pages.

The deployment of Docusaurus to GitHub pages is failing.
Check out the error from deploying Docusaurus page to GH Pages: https://github.com/anitab-org/anitab-forms-web/runs/3771335051

Config file: https://github.com/anitab-org/anitab-forms-web/blob/develop/.github/workflows/docs.yml
Docusaurus config: https://github.com/anitab-org/anitab-forms-web/blob/develop/docs/docusaurus.config.js

### Update [Required]
- [ ] Fix the Docusaurus configuration file in order for the release to work
- [ ] Modify email from docs.yml to use `opensource@anitab.org` instead of `actions@github.com`

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

1h

**Comment by Aniket762** [comment]
Hey, @isabelcosta I am interested. Can you please assign this to me? Being a first-timer to this org will be a great start for me!

**Comment by isabelcosta** [comment]
Hi @Aniket762 :) Sure, I'll assign to you!

**Comment by Aniket762** [comment]
Hey @isabelcosta, I have changed the `email` to `opensource@anitab.org` and username to `anitab-org`. I followed [this](https://docusaurus.io/docs/deployment).

 But I am getting `permission error`, I generated the key using `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` , then created a deployment key with the name `GH_PAGES_DEPLOY` then also it shows permission denied. 

Then I removed the `webfactory/ssh-agent@v0.5.0` flow and got the permission denied error again, in the logs which you have given had the error of repository was not found. 

Can you please guide me or give me some resources on what I should do next?

**Comment by isabelcosta** [comment]
@Aniket762 this https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions helped me a lot.

I would also encourage you to create a PR now if you already did the changes, so we can review it.

cc @codesankalp

**Comment by Aniket762** [comment]
> @Aniket762 this https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions helped me a lot.
> 
> I would also encourage you to create a PR now if you already did the changes, so we can review it.
> 
> cc @codesankalp

sure!
