### ISSUE TITLE
Add badge to README about Docusaurus documentation

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-web#169]
## Description

Docusaurus documentation is available at https://anitab-org.github.io/anitab-forms-web/ thanks to #168

## Mocks

![mentorship-backend README badges](https://user-images.githubusercontent.com/11148726/135931426-07509064-59d6-4025-bf94-8c5ace574a7b.png)

### Update [Required]
- [ ] Add badge with a link to Docusaurus on README. You can follow other projects example from the community such as [mentorship-backend](https://github.com/anitab-org/mentorship-backend)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation

30 min

**Comment by nlok5923** [comment]
Can I work on it.

**Comment by codesankalp** [comment]
Assigning you @nlok5923

**Comment by isabelcosta** [comment]
@codesankalp @nlok5923 I labeled this as a `first-timers-only` issue, since it is a very simple issue a newcomer can tackle. You have contributed before with https://github.com/anitab-org/anitab-forms-web/pull/110. Thank you for your eagerness to contribute! I will unassign so we can give a newcomer the chance to work on an issue for this repository. We can come with more issues that you can work on :)

**Comment by sharur7** [comment]
Can I work on this issue? @isabelcosta
