### ISSUE TITLE
Add link with icon to our AnitaB.org Open Source Medium

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/open-source-programs-web#171]
## Description

As an admin,
I need our Medium blog to be in the social media links on Docusaurus,
so that I can promote our blog to our contributors.

We want to see the medium link to our AnitaB.org Open Source on the Docusaurs page footer.
Our Medium publication: https://medium.com/anitab-org-open-source
Our Docusaurus documentation: https://anitab-org.github.io/anitab-forms-web/

## Mocks

You can find this in the footer:
![docusaurus page footer](https://user-images.githubusercontent.com/11148726/136611075-679c93b8-6763-4056-afad-1c9a7bd1a902.png)

### Update [Required]
- [ ] Add Medium icon with link to our blog on Docusaurus page footer.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

30 min

**Comment by ToluAkin** [comment]
Hi @isabelcosta Can I work on this?

**Comment by isabelcosta** [comment]
Yes @ToluAkin :) I will assign it to you

**Comment by isabelcosta** [comment]
@ToluAkin you might not see the same social icons as it is in the issue description. This is because I saw this in the mentorship repositories. It's ok, if for this website you add it as a community link in the footer, below github and zulip link

![anitab forms web footer](https://user-images.githubusercontent.com/11148726/136617497-20b29b51-92c1-4d80-9d11-86fb648f436b.png)

**Comment by ToluAkin** [comment]
Noted @isabelcosta
