### ISSUE TITLE
Tests: Add tests for checking input validations on Register form.

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#173]
### Describe the solution you'd like

- Assert if validation check pops up for  empty username or email.
- Assert if validation check pops up if the password and email are not in correct format.
- Assert if validation check pops up if passwords are not same

### Describe any other information required

Use jest for testing .
More info on testing https://jestjs.io/docs/tutorial-react

### Additional context

This can be [useful](https://github.com/anitab-org/bridge-in-tech-web/pull/88/files).

**Comment by Code-Aditya-14** [comment]
Can I work on this issue @Aaishpra

**Comment by jennypoon** [comment]
I would like to give this a shot

**Comment by isabelcosta** [comment]
Thank you so much for creating this @Aaishpra 🙌🏾 
I assigned it to you @jennypoon :)
