### ISSUE TITLE
Tests: Write tests for checking input validations if fields are empty in Login form

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#174]
### Describe the solution you'd like

- Assert if validation check pops up for  empty username.
- Assert if validation check pops up for empty email.

### Describe alternatives you've considered

Use jest for testing .
More info on testing https://jestjs.io/docs/tutorial-react

### Additional context

This can be [useful](https://github.com/anitab-org/bridge-in-tech-web/pull/88/files).

**Comment by groopav** [comment]
Can I please work on this issue?

**Comment by Aaishpra** [comment]
Go ahead
