### ISSUE TITLE
Add roadmap link to the documentation section in readme

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#181]
## Is your feature request related to a problem? Please describe

We can get the idea of the features and project status by  the project roadmap, hence a link to the same should be present in the readme.

## Describe the solution you'd like

Add the roadmap link under documentation section in Readme.

**Comment by msaini28r** [comment]
@Aaishpra I would like to work on the issue.

**Comment by isabelcosta** [comment]
@msaini0r before working on this could you please address my comments in your open pull request

**Comment by gayatrib** [comment]
@isabelcosta @Aaishpra is this issue still open?

**Comment by Aaishpra** [comment]
> @isabelcosta @Aaishpra is this issue still open?

Assigned ya!!

**Comment by Naliaka** [comment]
Have commit the link: docs: add roadmap link to the documentation section in readme
https://github.com/Naliaka/anitab-forms-web

**Comment by Aaishpra** [comment]
> Have commit the link: docs: add roadmap link to the documentation section in readme https://github.com/Naliaka/anitab-forms-web

Please send a PR instead of commit.

**Comment by Samridhi-98** [comment]
@Aaishpra @isabelcosta   is this issue still open?
I would like to work on it.

**Comment by Aaishpra** [comment]
> @Aaishpra @isabelcosta   is this issue still open?
> I would like to work on it.

Sure go for it
