### ISSUE TITLE
Planning: Open Source Programs ER diagram

### ISSUE THREAD

**Issue by bismitaguha** [anitab-org/open-source-programs-web#2]
Discussion for the initial ER diagrams of the application.

**Comment by bismitaguha** [comment]
[DB structure](https://whimsical.com/54vvNLcoYqHzeFqEpyPAKq)
![db-structure-osp (1)](https://user-images.githubusercontent.com/43119923/83338581-4d841880-a2e3-11ea-9181-0f0101da10b0.png)

**Comment by abha224** [comment]
closing this issue as the ER diagram was approved and finalized.
