### ISSUE TITLE
Registration mocks UI

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/open-source-programs-web#3]
## Description
As a User,
I need to register to OSP,
so that I can login.

## Mocks
*Need to be created*

### Minimum Needed [Required]
- [x] Field to input email 
- [x] Field to input password
- [ ] Field to input first name
- [ ] Field to input last name

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by bismitaguha** [comment]
### Login Page
![Screenshot from 2020-05-20 01-07-25](https://user-images.githubusercontent.com/43119923/82370820-c7401a80-9a36-11ea-9a97-c54f69f38504.png)
### Register Page
![Screenshot from 2020-05-20 01-07-42](https://user-images.githubusercontent.com/43119923/82370825-ca3b0b00-9a36-11ea-9b7f-98fb02fbac25.png)

**Comment by mayburgos** [comment]
@bismitaguha The only feedback is we need the application title somewhere.

**Comment by Monal5031** [comment]
Agree with @mayburgos , Create a generic navbar as well

**Comment by bismitaguha** [comment]
## General Navbar
![navbar](https://user-images.githubusercontent.com/43119923/83058403-f0cff600-a075-11ea-94a1-849b1d9fe31a.png)
## Navbar when not Logged In
![navbar-out](https://user-images.githubusercontent.com/43119923/83058525-1e1ca400-a076-11ea-9f8e-3cf931acdfe6.png)

@mayburgos @Monal5031 @abha224 Please review. :smiley:

**Comment by abha224** [comment]
@bismitaguha can you move the settings and logout display to below the navbar? The navbar looks good otherwise!
Also, is the login page going to be the landing page of the website?

**Comment by bismitaguha** [comment]
A check will be done on logged-in state and based on that a redirect will be made to the login page or homepage! @abha224

**Comment by abha224** [comment]
closing this issue since the mocks were approved.
