### ISSUE TITLE
UI: Design a 404 page for default redirects

### ISSUE THREAD

**Issue by bismitaguha** [anitab-org/open-source-programs-web#33]
### Is your feature request related to a problem? Please describe.
Currently, wrong URLs redirect to a general page but the correct redirect should be to a `404: Not found` page. We need the design of such a page and a change in the URL `Routes.js`

### Describe the solution you'd like
- Design a 404 page
- Change route URL to Redirect to `/404` on wrong URLs

### Definition of Done
- [ ] A 404 error page mockup
- [ ] A change in `Routes.js` for proper redirect

**Comment by Akanksha1212** [comment]
Hi @bismitaguha, I would like to work on this.

**Comment by bismitaguha** [comment]
Wonderful @Akanksha1212 You may go ahead!!!

**Comment by abha224** [comment]
@Akanksha1212 Hi! How's the progress on this issue?

**Comment by Akanksha1212** [comment]
Hi @abha224, I am working on it.

**Comment by Akanksha1212** [comment]
Hi, Sorry but I don't have bandwidth to work on this rn. Will look for other issues. Making it available for others.

**Comment by ParvathiRajpal** [comment]
Hi, May I take up this issue?

**Comment by Aaishpra** [comment]
@bismitaguha Can i work on this

**Comment by Aaishpra** [comment]
Hey @bismitaguha while designing the 404 Error page i thought to give it a go back home button but since the home page is not yet available so should i just skip it or give a button to back to login page.

**Comment by shivanii10** [comment]
@bismitaguha  i want to work in this , could you please guide me?

**Comment by bismitaguha** [comment]
@shivanii10 This is already assigned. Look for other issues!! Check out the backend repo also

**Comment by shivanii10** [comment]
> @shivanii10 This is already assigned. Look for other issues!! Check out the backend repo also

ok
