### ISSUE TITLE
Use a code formatter for standardising the code style

### ISSUE THREAD

**Issue by sidvenu** [anitab-org/open-source-programs-web#34]
### Is your feature request related to a problem? Please describe.
It will be difficult to enforce a coding style as the repo grows bigger and gets more PRs.

### Describe the solution you'd like
We must use a code formatter (ideally, opinionated one like https://prettier.io/) to handle that.

### Describe alternatives you've considered
We can have unopinionated code formatters, but that still places much of the burden of coding style to the end-developer.

**Comment by INNOVATIVEGAMER** [comment]
@sidvenu or @isabelcosta  can you assign me on this issue.
I will add prettier as dependency and npm scripts for formatting and checking for the prettier formatter.

**Comment by Aaishpra** [comment]
Closing this because we have #75
