### ISSUE TITLE
login validation notifications

### ISSUE THREAD

**Issue by abha224** [anitab-org/open-source-programs-web#37]
### Describe the bug
Currently, when the user logs in, there is no message displayed in case the username is invalid or if the password and username don't match.

### Expected behavior
An appropriate message should be displayed in case of errors.

**Comment by ksraj123** [comment]
@bismitaguha @abha224 I don't see a PR associated with this issue, I would like to do this if someone is not working on it already. Thanks

**Comment by abha224** [comment]
@ksraj123 Hi! yes sure, you can go ahead and work on this issue! :)

**Comment by somayaj** [comment]
Can this be worked?

**Comment by chinmaym07** [comment]
Hey @abha224 Can i try this issue.?

**Comment by Aditi-Roy-coder** [comment]
Can I please work on this issue? @abha224

**Comment by Aaishpra** [comment]
@ksraj123 are you still working on the issue?

**Comment by vj-codes** [comment]
Unassigning @ksraj123  due to inactivity.
If you would like to work again do let us know:)
This issue is available to all currently 🚀

**Comment by Rahulm2310** [comment]
@vj-codes I would like to take up this issue.

**Comment by Aditi-Roy-coder** [comment]
@vj-codes Can I please work on this issue?

**Comment by Rahulm2310** [comment]
@vj-codes I would like to continue with this issue 😊

**Comment by vj-codes** [comment]
Assigning you @Rahulm2310 
Happy coding!
@Aditi-Roy-coder you can go through other available issues for a great start!

**Comment by Rahulm2310** [comment]
Thanks @vj-codes

**Comment by Rahulm2310** [comment]
@vj-codes can you explain this a little. Are the specific error messages sent from the backend and I just need to show them in the UI ?

**Comment by vj-codes** [comment]
@Rahulm2310 I don't have much knowledge of this project , I'm just helping with the part of assigning/unassigning and labelling as there was no one active here.

@sidvenu @abha224 @bismitaguha can only help you here 
Are there any messages in backend though?

**Comment by Rahulm2310** [comment]
@vj-codes  Seems so as every thing is handled at the backend, we are getting custom error messages from there only. @sidvenu @abha224 @bismitaguha guys please help

**Comment by Rahulm2310** [comment]
I think we are already showing error messages when a user enters invalid username or a valid username &  mismatching password. 
![login-msg](https://user-images.githubusercontent.com/54268438/105469655-99466080-5cbe-11eb-9493-3456f4070448.JPG)
Although, for errors like network errors we are not showing any error notifications. Can someone point out what for what more specific use cases we need to show error messages ?

**Comment by Aaishpra** [comment]
@Rahulm2310 I am not sure but i think this issue demands some different error message to be shown when the username is invalid or if the password and username don't match, for example the error message shown for 2nd case i mentioned can be "sorry the username and password you entered don't match."
Does this make sense?

**Comment by Rahulm2310** [comment]
@Aaishpra If so then specific error messages should be sent from the backend only.

**Comment by Aaishpra** [comment]
> @Aaishpra If so then specific error messages should be sent from the backend only.

I am not quite sure, but I too believe that this should be handled at backend.
@abha224 can you help us?

**Comment by Aaishpra** [comment]
@Rahulm2310 please unassign from this issue as you got assigned to #70 (please try to follow contribution guidelines) and I see no updates regarding your work in the issue.

Cc: @isabelcosta

**Comment by Rahulm2310** [comment]
@Aaishpra As you can see I tried tagging several author/members regarding the issue but got no response from any one. (I think the last few comments explains it all). I am unassigning myself. Thanks 🙂

**Comment by codesankalp** [comment]
@Rahulm2310, @Aaishpra , @isabelcosta  I have checked it, and as the login is just a POST request from the web, the backend just returns token if credentials are correct else it returns `no active account found`. This message response must be handled from the backend.

**Comment by Rahulm2310** [comment]
Yes, we were thinking the same. Thanks @codesankalp

**Comment by Aaishpra** [comment]
Closing this as this issue should be covered at the backend.
