### ISSUE TITLE
Special characters missing from Password Regex

### ISSUE THREAD

**Issue by bismitaguha** [anitab-org/open-source-programs-web#38]
### Describe the bug
Currently, a few special characters are not covered in the password Regex.

### To Reproduce
1. Go to 'register user'
2. Enter a password having characters '.', '()', etc
3. Press **Register**
4. See password error still shown

### Expected behavior
All the special characters should be acceptable

### Screenshots
N/A

### Additional context
Solve this by adding support for these characters in the Regex.

**Comment by saideepesh000** [comment]
Can I try this issue? @bismitaguha

**Comment by bismitaguha** [comment]
Yes @saideepesh000 sure! Before making the PR just list down the characters or changes you are adding.

**Comment by saideepesh000** [comment]
@bismitaguha, are we going to use all the special characters listed [here](https://tools.oratory.com/altcodes.html) or just those are directly visible on the keyboard.

**Comment by saideepesh000** [comment]
@bismitaguha , I think this works, you can try here [regex101](https://regex101.com/)

^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\[\]~`!@#$%^&*?\\/>.<,"':;}{|+=_()-])[A-Za-z\d[\[\]~`!@#$%^&*?\\/>.<,"':;}{|+=_()-]{12,}$

**Comment by bismitaguha** [comment]
It's not working there @saideepesh000 . Do make the PR so we can test it out!!
