### ISSUE TITLE
Bug: update the username properly 

### ISSUE THREAD

**Issue by abha224** [anitab-org/open-source-programs-web#44]
### Describe the bug
Currently the edit profile functionality is not working as expected. The first character does not get deleted on backspace. This has to be modified accordingly in the frotend part so that the user an easily update the username.

### To Reproduce
1. login to osp
2. Click on dashboard
3. select the pencil icon to edit
4. try to edit the username

### Expected behavior
The username should be edited without retention of any previous values

### Screenshots
![user updates](https://user-images.githubusercontent.com/39526159/88670593-4f593500-d0f6-11ea-9ca6-395b9a8eb3b0.gif)

**Comment by saideepesh000** [comment]
@abha224, Can I try this.

**Comment by bismitaguha** [comment]
@saideepesh000 Go ahead!! Also thanks for taking interest in this project and contributing! :tada:

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 Go ahead!! Also thanks for taking interest in this project and contributing! 🎉

@bismitaguha, Thanks

**Comment by saideepesh000** [comment]
@bismitaguha, @abha224, Please help me with the issue. while setting up the ops-backend, I ran into this error, I've done all the migrations too.

![Screenshot (250)](https://user-images.githubusercontent.com/43727167/89064033-da505e80-d386-11ea-9365-ff225364e358.png)

And this was the console error

![Screenshot (251)](https://user-images.githubusercontent.com/43727167/89064457-aa558b00-d387-11ea-894a-5f4cdcc4f962.png)

**Comment by bismitaguha** [comment]
try `api/` @saideepesh000

**Comment by saideepesh000** [comment]
@bismitaguha , it's showing 

"HTTP 403 Forbidden
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Authentication credentials were not provided."
}
"

**Comment by bismitaguha** [comment]
You haven't logged in this means. Login to the backend!

**Comment by saideepesh000** [comment]
@bismitaguha,  

> 
> 
> You haven't logged in this means. Login to the backend!

u mean to create a "superuser" in django

**Comment by bismitaguha** [comment]
Yess create an user and login

**Comment by saideepesh000** [comment]
@bismitaguha, On front-end also when I register to create an account, I got an error showing "Unauthenticated senders not allowed".

**Comment by bismitaguha** [comment]
Do create from the terminal a superuser!

**Comment by saideepesh000** [comment]
> 
> 
> Do create from the terminal a superuser!

I got it :), thanks, One doubt, In any Django project, irrespective of front-end "Register/Sign up", we need to create a "superuser", and with that "superuser" we need to log in, am I right?

**Comment by bismitaguha** [comment]
Yes!!!

**Comment by saideepesh000** [comment]
@bismitaguha , is this OK.

![edit_username](https://user-images.githubusercontent.com/43727167/89097318-9c415200-d3fb-11ea-8ac2-1411b3ba2569.gif)

**Comment by bismitaguha** [comment]
Looks good to me....please make a PR
