### ISSUE TITLE
Profile UI for user

### ISSUE THREAD

**Issue by Monal5031** [anitab-org/open-source-programs-web#5]
## Description
As a User,
I am able to view and edit my profile on OSP,
so that I can display my latest details.

## Mocks
*Need to be created*

### Update [Required]
- [x] Fields showing the details filled in already.
- [x] A button to edit a particular field

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by bismitaguha** [comment]
## User Dashboard
- **GitHub Stats** is a NICE TO HAVE.
- Included View for the **Logout** & **Settings** options.
![OSP-UI-User Dashboard](https://user-images.githubusercontent.com/43119923/83057846-190b2500-a075-11ea-8ff2-0b3982278976.png)

### Some possible additions
- More details to be asked from users.
- **NICE TO HAVE:** Better detailed stats from Zulip and GitHub (stream-wise, repository-wise)

@mayburgos @Monal5031 @abha224 discussions on these topics are required!!!

**Comment by abha224** [comment]
@bismitaguha 
I have a few thoughts: 
1) some of the headings could be renamed like, general information-> profile, user type -> role
2) under the information, we can include a skills section(can be named something else as well) to indicate their technical interests or the technical role they assume. We can also add a field where they can display which program they are applying for currently.
3) Can you describe more about the update button in the stats? If the information regarding the number of messages and prs is being retrieved, I'm guessing that the update option will be necessary only for updating the usernames. If that's the case, we can shift the usernames to the general information section and remove the update button. 
4) Under the filled forms, I feel that only form name and created date/update date would be necessary.

**Comment by bismitaguha** [comment]
@abha224 

> 2. under the information, we can include a skills section(can be named something else as well) to indicate their technical interests or the technical role they assume. We can also add a field where they can display which program they are applying for currently.

Regarding the program part, we are not covering this GSoC. @mayburgos suggested we should remove those, as programs are not a part of MVP. So only forms and filtering based on forms

> 3. Can you describe more about the update button in the stats? If the information regarding the number of messages and prs is being retrieved, I'm guessing that the update option will be necessary only for updating the usernames. If that's the case, we can shift the usernames to the general information section and remove the update button.

All that information will be generated automatically through Zulip scripts, so combining them would complicate the APIs. UPDATE would run the scripts and update the information, that cannot be filled by user themselves.

**Comment by abha224** [comment]
> Regarding the program part, we are not covering this GSoC. @mayburgos suggested we should remove those, as programs are not a part of MVP. So only forms and filtering based on forms

@bismitaguha oh okay, cool then!

> All that information will be generated automatically through Zulip scripts, so combining them would complicate the APIs. UPDATE would run the scripts and update the information, that cannot be filled by user themselves.

got it :+1:

**Comment by bismitaguha** [comment]
### Dashboard view
![OSP-UI-Dashboard (1)](https://user-images.githubusercontent.com/43119923/83338614-b23f7300-a2e3-11ea-9b30-ce1bf1c5810a.png)
@abha224 @Monal5031 @mayburgos This is the updated view based on suggestions. For the admins we won't have the forms filled and stats part.

**Comment by abha224** [comment]
Closing this issue since the dashboard UI code is already merged.
