### ISSUE TITLE
Create the config.yml file for the Welcome Bot

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#59]
### Description
As a first time contributor,
I need a bot to help guide my first contribution,
so that I can follow this org's contribution guidelines.

### Mocks
![image](https://user-images.githubusercontent.com/66299533/93045943-2c6aec00-f676-11ea-8dd7-88f4ea670894.png)

### Acceptance Criteria

- [ ] newIssueWelcomeComment is complete with the correct links to this repo.

- [ ] newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.

- [ ] firstPRMergeComment is complete.

### Additional context
great for first-timers

**Comment by Aaishpra** [comment]
@bismitaguha @annabauza @sidvenu @abha224 can someone have a look at this issue and tell me if I can work on this. Thanks in advance.

**Comment by ankitapuri** [comment]
@Aaishpra  can I work on this issue

**Comment by Aaishpra** [comment]
Hey @ankitapuri Please accept my apologies,but can you look for some other issues in the project, as i have already done my work for this issue and would submit a PR as soon i am assigned to this.
Also i am just a contributor to this repo so can't really assign issues to anyone.😁

**Comment by ankitapuri** [comment]
Ohk no issues

**Comment by abha224** [comment]
Hi @Aaishpra ! I think this issue would require some discussion around the content of the bot from the project managers of the community. Tagging @anitab-org/open-source-progs-managers for adding their comments.

**Comment by Aaishpra** [comment]
> Hi @Aaishpra ! I think this issue would require some discussion around the content of the bot from the project managers of the community. Tagging @anitab-org/open-source-progs-managers for adding their comments.

Sure, and thanks for tagging the team😊

**Comment by Aaishpra** [comment]
@bismitaguha @sidvenu can you have look here. Thanks

**Comment by aditmehta9** [comment]
@Aaishpra assigned you.

**Comment by Amulya-coder** [comment]
Alright, @Aaishpra this issue is already existing, thanks for informing :) as currently, no one is working on this. I would like to be assigned.

**Comment by Aaishpra** [comment]
> Alright, @Aaishpra this issue is already existing, thanks for informing :) as currently, no one is working on this. I would like to be assigned.

Assigned you 🎉

**Comment by Amulya-coder** [comment]
@Aaishpra can I simultaneously work on [this](https://github.com/anitab-org/open-source-programs-backend/issues/89) issue also as both are the same I will create the pr of that also while working on this issue so these both get solved what say?

**Comment by Aaishpra** [comment]
@Amulya-coder i would have assigned you to both issues at the same time because they were in different repos( ie web and backend) but since you are already a contributer in the backend repo(and this issue is meant for first timers only) i would recommend you to work on this here (ie at web) and leave the other one for newcomer. If you want to work on any other issue at the backend(not any first timer) ask me for it. I will assign you there😉

Ps. Thanks for opening this issue in the backend.
