### ISSUE TITLE
Coding : Develop Dark-Mode

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/open-source-programs-web#62]
### Is your feature request related to a problem? Please describe.
No. It's not related to a problem .But it's an additional feature as almost every web-app today has a dark-mode feature.

### Describe the solution you'd like
To Implement Dark-Mode

If it's a valid feature .Please assign this to me .

**Comment by Rahulm2310** [comment]
@chinmaym07 agreed that dark mode is a feature in most of the established apps today. But at this moment, I don't think dark mode functionality should be in our priority list. Rest is in hands of maintainers :)

**Comment by isabelcosta** [comment]
Hey @chinmaym07 thank you for proposing this idea :D and @Rahulm2310 for your suggestion!

This is a good idea, however, we would like to prioritize some PRs that open and we need to triage them. Before we start implementing new ideas, perhaps you could help review some of the PRs we have open and that need review. Here's a selection of it: https://github.com/anitab-org/open-source-programs-web/pulls?q=is%3Apr+is%3Aopen+label%3A%22Status%3A+Needs+Review%22

We would really appreciate if you could help with this :)

**Comment by chinmaym07** [comment]
> Hey @chinmaym07 thank you for proposing this idea :D and @Rahulm2310 for your suggestion!
> 
> This is a good idea, however, we would like to prioritize some PRs that open and we need to triage them. Before we start implementing new ideas, perhaps you could help review some of the PRs we have open and that need review. Here's a selection of it: https://github.com/anitab-org/open-source-programs-web/pulls?q=is%3Apr+is%3Aopen+label%3A%22Status%3A+Needs+Review%22
> 
> We would really appreciate if you could help with this :)

Yes .. thankyou @isabelcosta ..I completely agree with you & I will start reviewing open pr's ..☺️👍🏻

**Comment by Rahulm2310** [comment]
Thanks @isabelcosta ! I will also help in reviewing some open PRs.

**Comment by isabelcosta** [comment]
Thank you a lot @Rahulm2310 @chinmaym07
