### ISSUE TITLE
Docs: Modifying setup instructions

### ISSUE THREAD

**Issue by khushishikhu** [anitab-org/open-source-programs-web#63]
### Is your feature request related to a problem? Please describe.
In the setup instructions for starting the server ` cd open-source-programs-web`  this command is quite confusing for new developers and doesn't required here

### Describe the solution you'd like
This line should be removed because once we clone the project, we are already in that repository.

**Comment by khushishikhu** [comment]
I would like to work on this issue. Can someone assign me for this ?

**Comment by Rahulm2310** [comment]
@khushishikhu I admire your consideration for new developers, but I don't think a single command line can confuse anyone. In fact, this way new developers get to learn about command line interface which a developer uses everyday.
