### ISSUE TITLE
Fix Typos in Readme and add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by INNOVATIVEGAMER** [anitab-org/open-source-programs-web#64]
### Describe the bug

1. Spelling mistakes and some commas are missing in the readme file.
2. Missing link to the contributing guidelines.
3. Add CONTRIBUTING.md file in .github folder

### Screenshots
![Editing open-source-programs-web_README md at develop · anitab-org_open-source-programs-web - Google Chrome 23-01-2021 12_46_14](https://user-images.githubusercontent.com/55017197/105571810-1a622e00-5d79-11eb-88d7-398a7300df7b.png)

**Comment by INNOVATIVEGAMER** [comment]
@isabelcosta  please can you assign me on this issue so I can make required changes.

**Comment by isabelcosta** [comment]
@INNOVATIVEGAMER I am not sure about what are the spelling mistakes, but I agree with the missing link. I will assign this to you, I can review the spelling mistakes in the PR :) Thank you for creating this!
