### ISSUE TITLE
Too many warnings

### ISSUE THREAD

**Issue by sagar-barapatre** [anitab-org/open-source-programs-web#67]
### Describe the bug
The applications runs with too many warnings.

### To Reproduce
1. Go to each and every file where the warning is given
2. Go on that line where the warning is given.
3. See the warning the resolve that.

### Expected behavior
After resolving all the warnings we get to run the applications without any warnings
### Screenshots
![Screenshot 2021-01-28 at 8 36 58 AM](https://user-images.githubusercontent.com/64516304/106084504-7eec0700-6144-11eb-8c4f-1ee5cc84c297.png)

### Desktop (please complete the following information):
 - OS: iOS
 - Browser: safari, chrome
 - Version: 22

**Comment by Rahulm2310** [comment]
@sagar-barapatre I suggest you to wait until a maintainer confirms and assigns the issue to you before creating a pull request. 
Also, please remove `Please approve this issue and assign this to me.` from the issue description. Thanks 🙂

**Comment by isabelcosta** [comment]
Thank you @Rahulm2310 for mentioning the contribution guidelines to @sagar-barapatre ! @Rahulm2310 is correct, that we prefer if you wait for issue approval before creating a PR. Thank you for creating the issue, that was the first step :)
This is a good issue @sagar-barapatre . I asked you some changes in the PR itself.

**Comment by sagar-barapatre** [comment]
Thank you so much @isabelcosta @Rahulm2310 and sorry for not waiting until the maintainer confirms and assigns this issue to me.

**Comment by sagar-barapatre** [comment]
Thank you so much @isabelcosta 😀

**Comment by subodhk01** [comment]
What's the status in this issue? I would love to help

**Comment by sagar-barapatre** [comment]
@subodhk01 The PR has already been made for this issue by me and it's under review.

**Comment by isabelcosta** [comment]
@subodhk01 you can totally help! You can help to review the PR, please :) We need more reviewers

**Comment by subodhk01** [comment]
Sure I would love to review it

**Comment by codesankalp** [comment]
Closing this issue as it is fixed after adding QA-Checks and linting.
