### ISSUE TITLE
Add the setup tutorial video to Readme.md

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-web#70]
### Is your feature request related to a problem? Please describe.
Newcomers find it difficult to setup the project locally on their system due to vague instructions.

### Describe the solution you'd like
Add a setup tutorial video to Readme.md. 
The [video](https://youtu.be/_b2RQGbYN9w) is already been recorded by @codesankalp.

**Comment by Rahulm2310** [comment]
@isabelcosta I think this can be a good first-timer issue.

**Comment by isabelcosta** [comment]
Yes totally! @Rahulm2310 
Thank you for creating this 🙌 

And again @codesankalp thank you so much for the video!

**Comment by Rahulm2310** [comment]
@isabelcosta Can I work on this as I have not contributed to the repo as well

**Comment by isabelcosta** [comment]
Sure @Rahulm2310 ! I will assign this to you!

**Comment by Amulya-coder** [comment]
@isabelcosta this issue is addressed in #71 can you please check it once! . Thanks 🙂.

**Comment by isabelcosta** [comment]
@Amulya-coder it's ok to have it mentioned also in the setup, since it's related to it, like a footnote of the setup section ;) The issue you mentioned, I updated it and it has to do with documentation section in the readme
