### ISSUE TITLE
Bug: Incorrect active tab on refresh

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-web#74]
### Describe the bug
After refreshing the page, the menu shows active tab as Dashboard even if the route is at /forms or /submission

### To Reproduce
1. Go to http://localhost:3000/submission
2. Refresh page

### Expected behavior
Active tab should be the same as the active route.

### Screenshots
![osp-tab-issue](https://user-images.githubusercontent.com/54268438/107563745-747f4200-6c07-11eb-858b-49d965353b43.gif)

### Desktop (please complete the following information):
 - OS: Any
 - Browser : Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@isabelcosta Can you please confirm/approve this issue? This can be a good `First Timers only` issue.

**Comment by Aaishpra** [comment]
> @isabelcosta Can you please confirm/approve this issue? This can be a good `First Timers only` issue.

Issue confirmed

**Comment by jeeva2812** [comment]
@Aaishpra I am willing to try. Can you please assign me for this issue?

**Comment by Aaishpra** [comment]
> @Aaishpra I am willing to try. Can you please assign me for this issue?

Assigned you 
Happy coding 👍🏻

**Comment by jeeva2812** [comment]
@Aaishpra @Rahulm2310 I have created PR, please do review.
