### ISSUE TITLE
Add Code Linter and Formatter to enhance code quality and maintain consistency.

### ISSUE THREAD

**Issue by jalajcodes** [anitab-org/open-source-programs-web#75]
### Is your feature request related to a problem? Please describe.
It is necessary for a project to have clear consistent coding conventions. Besides that linting is also very helpful for finding certain classes of bugs and fixing them before runtime.

### Describe the solution you'd like
[Eslint](https://eslint.org) and [Prettier](https://prettier.io) are by far the most popular code linter and formatter for Javascript.

* Integrate Eslint into the project
* Integrate Prettier into the project
* Make Eslint work with prettier i.e. Eslint for linting and Prettier for formatting code
* Add a brief description about them in the project readme. 
* Add Github workflows to ensure the guidelines are followed by every contributor.

### Describe alternatives you've considered
- [Rome](https://rome.tools/)
- We can also have a `.editorconfig` file in the project. EditorConfig's role is to configure the code editor so that the code we write is already formatted while Prettier will format the already written code.

### Additional context
WesBos maintains [this nice repo](https://github.com/wesbos/eslint-config-wesbos) related to eslint and prettier and we can take some ideas from there.

**Comment by jalajcodes** [comment]
@isabelcosta Please add labels to this issue. Also, I'd like to work on it. 😀

**Comment by isabelcosta** [comment]
Sure @jalajcodes :)

**Comment by Rahulm2310** [comment]
@isabelcosta isn't #36 fixing the formatting issue i.e adding `prettier`

**Comment by isabelcosta** [comment]
Uhhhh I guess, thank you for pointing that our @Rahulm2310 !
I will close that though since the contributors are no longer active.
closes #36

**Comment by Aaishpra** [comment]
@jalajcodes if no-one replies on [your comment](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs/topic/Open.20Sessions/near/226677800) on Zulip in 2-3 days then you can go on and submit the PR. Although we decided to discuss this matter,but I think not many people are interested in the discussion so you can go forward with what you consider to be best for the project, and then we all can review it.

**Comment by jalajcodes** [comment]
> @jalajcodes if no-one replies on [your comment](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs/topic/Open.20Sessions/near/226677800) on Zulip in 2-3 days then you can go on and submit the PR. Although we decided to discuss this matter,but I think not many people are interested in the discussion so you can go forward with what you consider to be best for the project, and then we all can review it.

Ok 😉
