### ISSUE TITLE
Error: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by subodhk01** [anitab-org/open-source-programs-web#77]
### Describe the bug
First time I started the project and recieved this error

### To Reproduce
1. npm i
2. npm start
3. Go to http://localhost:3000/

### Screenshots
<img width="1046" alt="Screenshot 2021-02-13 at 15 41 59" src="https://user-images.githubusercontent.com/19875783/107847475-0490d780-6e12-11eb-9c2d-ba225dd0e9fb.png">

### Desktop (please complete the following information):
 - OS: MacOS BigSur 11.0.1
 - Browser Chrome

**Comment by subodhk01** [comment]
Hey @isabelcosta , Can you approve this issue? and also if approved, Can I work on this issue?

**Comment by subodhk01** [comment]
Ohh okhay, there was a problem with my backend server.

**Comment by isabelcosta** [comment]
that's interesting @subodhk01 ! what was the issue? So that, if anyone finds the same issue, your answer can perhaps help them

**Comment by codesankalp** [comment]
@isabelcosta this error comes when the backend server is not running and a request to the API returns undefined.

**Comment by jalajcodes** [comment]
> @isabelcosta this error comes when the backend server is not running and a request to the API returns undefined.

These are the cases where typescript shines out... anyways I think we should fix it so it doesn't happen with anyone else (show an error maybe?)

**Comment by subodhk01** [comment]
I agree @jalajcodes , we can show something that makes it clear for what the error is

**Comment by Rahulm2310** [comment]
yes, we should render a custom error message like `Network Error `or something when data is undefined.
