### ISSUE TITLE
docs: Include licence section in Readme

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-web#78]
### Is your feature request related to a problem? Please describe.
 It's good to mention about the license under which the organization follows. Currently, there is no licence added in the readme.

### Describe the solution you'd like
Add license section in the readme this is a great way to encourage more free, open-source code.

### Additional context
Here's is the link: https://github.com/anitab-org/open-source-programs-backend/blob/develop/LICENSE

**Comment by ayan-biswas0412** [comment]
@Amulya-coder can I work in this issue ? I will love to.🥰 contribute in this community

**Comment by Amulya-coder** [comment]
Sure @ayan-biswas0412, Welcome to the community🎊.

**Comment by Amulya-coder** [comment]
@isabelcosta can you please label this issue and assign it to @ayan-biswas0412.

**Comment by ayan-biswas0412** [comment]
Thank you @Amulya-coder 😁 I will love to contribute in this organisation in future also and I have made a PR #79 for this license addition

**Comment by Amulya-coder** [comment]
@ayan-biswas0412  I suggest when contributing to an open-source project, please wait for a maintainer to assign you the issue before creating a pull request. I think the maintainers also respect the fact that we all are excited to contribute to open source but be patient. Please have a look at the [contributing guidelines](https://github.com/anitab-org/open-source-programs-web/blob/develop/.github/CONTRIBUTING.md) of the project. Thanks 🙂

**Comment by ayan-biswas0412** [comment]
@Amulya-coder yes I understand the fact and I am apologising for my fault , and I will not do it again .Thanks

**Comment by Rahulm2310** [comment]
@ayan-biswas0412 hey, don't feel sorry man! It is for a contributor's betterment so that their efforts not go in vain. Cheer up🙂

**Comment by isabelcosta** [comment]
@Amulya-coder thank you for highlighting the guidelines ❤️ 
@ayan-biswas0412 I just assigned to you, will review the PR soon.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 hey, don't feel sorry man! It is for a contributor's betterment so that their efforts not go in vain. Cheer up🙂

yeah, thanks man for your kind words and your organization is very kind to developers like us 🥰

**Comment by Rahulm2310** [comment]
@ayan-biswas0412 I am a contributor like you, nothing more than that 🙂
