### ISSUE TITLE
Feat : Moving the documentation to docusaurus

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-web#81]
### Is your feature request related to a problem? Please describe.
Current documentation is fine but with docusaurus , the documentation becomes more readable and maintainable

### Describe the solution you'd like
Moving the project's documentation to [docusaurus](https://v2.docusaurus.io/)

### Additional context
Link to the discussion [here ](https://anitab-org.zulipchat.com/#narrow/stream/237907-open-source-progs/topic/Documentation)

**Comment by Rahulm2310** [comment]
@isabelcosta I would like to work on this. Thanks 🙂

**Comment by Rahulm2310** [comment]
@isabelcosta @Aaishpra I have migrated all the pages from wiki to docusaurus. Here's the [link](http://osp-web-docs.surge.sh/). Please share your views. Thanks 🙂

**Comment by isabelcosta** [comment]
looks cool :) @Rahulm2310 please submit the PR so we can add reviews 🎉
