### ISSUE TITLE
Feature: Activate new registered users by making API request

### ISSUE THREAD

**Issue by codesankalp** [anitab-org/open-source-programs-web#83]
### Is your feature request related to a problem? Please describe.
For a complete basic authentication system, we need to activate the newly registered users.
When a newly registered user clicks on the activation link sent to the mail it results in a redirection to the Login Page.

### Describe the solution you'd like
Create a new URL in `urls.js` for activating user which will make a GET request to `http://127.0.0.1:8000/api/token_auth/activate/< uidb64 >/< token >`.

The email for activating user contains URL in this format:
`http://localhost:3000/< uidb64 >/< token >`.

So you have to add a Route to this URL also to parse it and make a request to the backend and display the response received from the backend.

### Additional context
This issue needs to be solved after solving this issue https://github.com/anitab-org/open-source-programs-backend/issues/81

### Estimation
1 hour.

**Comment by codesankalp** [comment]
@isabelcosta After solving these issues:
1. #83
2. https://github.com/anitab-org/open-source-programs-backend/issues/81

Registering new users will work perfectly.

Can you add labels to it?

**Comment by codesankalp** [comment]
I would like to work on this issue @isabelcosta .

**Comment by codesankalp** [comment]
@isabelcosta Can I start working on this as the login feature is not working?

**Comment by isabelcosta** [comment]
assigned to you @codesankalp
