### ISSUE TITLE
docs: Add Badges to readme

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/open-source-programs-web#84]
### Is your feature request related to a problem? Please describe.
Add Badges to readme.md.

### Describe the solution you'd like
Here's a few commonly used badges in our repositories: 
![image](https://user-images.githubusercontent.com/54268438/107982048-5e97c580-6fe9-11eb-8ad7-58ea512236fa.png)

Feel free to add some more if relevant. https://shields.io/category/activity

**Comment by Rahulm2310** [comment]
@isabelcosta Please label it as a `first timer` issue. Thanks 🙂

**Comment by NegiAkash890** [comment]
I would like to update the same .

**Comment by isabelcosta** [comment]
you want to work on this issue, is that what you mean @NegiAkash890 ? I will assign this to you :)
