### ISSUE TITLE
Feat: Deploy from Github Actions

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#86]
## Is your feature request related to a problem? Please describe.
Creation of deploy.yml file from Github Actions for temporary deployment of Pull request

## Describe the solution you'd like
Creation of deploy.yml file in .github/workflow category

**Comment by Aaishpra** [comment]
@isabelcosta please add labels to the issue and if you allow can i work on this while working on #10 simultaneously. (it's a big feature and it will take some time to be completed 😬while this issue requires less work)

**Comment by Rahulm2310** [comment]
@Aaishpra Let's give someone else a chance as you got assigned to #10 (please try to follow contribution guidelines).

**Comment by isabelcosta** [comment]
where would you deploy this project to @Aaishpra ?
Regarding working on this, if you had a PR waiting for review, it would be ok, but since you are still in progress we prefer that people focus on working on one at a time. Do you want to drop that other issue and work on this one instead?

**Comment by Aaishpra** [comment]
@isabelcosta sorry for this issue I got a bit confused with GitHub actions deploy and deploying to github-pages but now know both are same thing and we agreed on not deploying the project to github pages in the last session (issue of navigation) so there is no need of this issue.
Hence closing this and I will continue working on #10
