### ISSUE TITLE
docs: Improve Issue templates and Pull request templates

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/open-source-programs-web#89]
### Is your feature request related to a problem? Please describe.
As I saw in the Issue template there are descriptions like `A clear and concise description of what you want to happen.` which is also shown in the preview window unless I remove it manually so it was a time taking process, the description like above should be commented as they are for Author's eye only.

### Describe the solution you'd like
It should be commented like this `<!-- A clear and concise description of what you want to happen. -->`

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by Amulya-coder** [comment]
@isabelcosta Can you please label it as a `First Timers only issue.` Thanks 🙂

**Comment by shruti1421** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by isabelcosta** [comment]
@shruti1421 its assigned to you :)
