### ISSUE TITLE
Docs: Delete ISSUE TEMPLATE folder from .github

### ISSUE THREAD

**Issue by Aaishpra** [anitab-org/open-source-programs-web#96]
## Description

As an org admin or maintainer,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Update [Required]

    

- [ ] Delete .github/ISSUE_TEMPLATE
- [ ] Update the [new link](https://github.com/anitab-org/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) for bug_report.md in Contributing.md

## Definition of Done

All of the required items are completed.

- [ ]  Approval by 1 mentor.

### Estimation

0.5 hours

**Comment by tosimia** [comment]
May I be assigned to this task?

**Comment by Aaishpra** [comment]
Assigned @tosimiadesoye

**Comment by tosimia** [comment]
Thanks!

**Comment by Aaishpra** [comment]
@tosimiadesoye while deleting the issue template can you also change the current link for bug_report.md file mentioned in 8th point of [Contributing.md](https://github.com/anitab-org/open-source-programs-web/blob/develop/.github/CONTRIBUTING.md) to this [link](https://github.com/anitab-org/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by tosimia** [comment]
Okay, I'll
